sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

title: GodDai的博客
name: GodDai
#description: Minimalism is a jekyll theme for minimalist
copyright_time: 2020
avatar: https://avatars1.githubusercontent.com/u/27391645?s=460&u=bd4f111d53ed93f878bc70ee883e234c5312922a&v=4

github: https://github.com/goddai
rss: true

#theme: jekyll-theme-minimalism
remote_theme: showzeng/Minimalism

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock
